name: survey_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit==1.26.0
      - tensorflow==2.16.1
      - pandas
      - numpy
      - plotly
      - joblib
      - seaborn
      - matplotlib
      - scikit-learn
